positive_test_data = {
    1 : {
            'Tereshin' : {
                "region": "Tuymen",
                "registered": "2006-08-11",
                "last_login": "2023-11-28",
                "email": "Artemka08@gmail.com",
                "age": 17,
                },
            'Komarov' : {
                "region": "Novorossysk",
                "registered": "2022-05-07",
                "last_login": "2023-01-01",
                "email": "i_am_not_komarov@komarov.kom",
                "age": 42,
                },
            'Telegin' : {
                "region": "Arzamas",
                "registered": "2000-09-20",
                "last_login": "2023-09-06",
                "email": "Telegin.s@gmail.com",
                "age": 7,
                },
            'Nudga' : {
                "region": "Krasnodarsk",
                "registered": "2023-05-08",
                "last_login": "2023-05-09",
                "email": "Nudgavsky@vk.ru",
                "age": 15,
                },
        },
    2 : {
            'Tereshin' : {
                "region": "Tuymen",
                "registered": "2006-08-11",
                "last_login": "2023-11-28",
                "email": "Artemka08@gmail.com",
                "age": 17,
                },
            'Komarov' : {
                "region": "Novorossysk",
                "registered": "2022-05-07",
                "last_login": "2023-01-01",
                "email": "i_am_not_komarov@gmail.com",
                "age": 42,
                },
            'Telegin' : {
                "region": "Arzamas",
                "registered": "2000-09-20",
                "last_login": "2023-09-06",
                "email": "Telegin.s@gmail.com",
                "age": 7,
                },
            'Nudga' : {
                "region": "Krasnodarsk",
                "registered": "2023-05-08",
                "last_login": "2023-05-09",
                "email": "Nudgavsky@gmail.com",
                "age": 15,
                },
        },
    3 : {
            'Tereshin' : {
                "region": "Tuymen",
                "registered": "2006-08-11",
                "last_login": "2023-12-20",
                "email": "Artemka08@gmail.com",
                "age": 17,
                },
            'Komarov' : {
                "region": "Novorossysk",
                "registered": "2022-05-07",
                "last_login": "2023-12-20",
                "email": "i_am_not_komarov@gmail.com",
                "age": 42,
                },
            'Telegin' : {
                "region": "Arzamas",
                "registered": "2000-09-20",
                "last_login": "2023-12-20",
                "email": "Telegin.s@gmail.com",
                "age": 7,
                },
            'Nudga' : {
                "region": "Krasnodarsk",
                "registered": "2023-05-08",
                "last_login": "2021-05-09",
                "email": "Nudgavsky@gmail.com",
                "age": 15,
                },
        },
}

negative_test_data = {
    4 : {
        },
    5 : {
        'Tereshin' : {
            "region": "Tuymen",
            "registered": "2006-08-11",
            "last_login": "2023-12-20",
            "email": "Artemka08@gmail.com",
            "age": 17,
            },
        'Komarov' : {
            "region": "Novorossysk",
            "registered": "2022-05-07",
            "last_login": "2023-12-20",
            "email": "i_am_not_komarov(*)gmail.com",
            "age": 42,
            },
        'Telegin' : {
            "region": "Arzamas",
            "registered": "2000-09-20",
            "last_login": "2023-12-20",
            "email": "Telegin.s@gmail.com",
            "age": 7,
            },
        'Nudga' : {
            "region": "Krasnodarsk",
            "registered": "2023-05-08",
            "last_login": "2021-05-09",
            "email": "Nudgavsky@gmail.com",
            "age": 15,
            },
        },
    6 : {
        'Tereshin' : {
            "region": "Tuymen",
            "registered": "2006-08-11",
            "last_login": "2023-12-20",
            "email": "Artemka08@gmail.com",
            "age": 17,
            },
        'Komarov' : {
            "region": "Novorossysk",
            "registered": "2022-05-07",
            "last_login": "2023-12-20",
            "email": "i_am_not_komarov@gmail.com",
            "age": 42,
            },
        'Telegin' : {
            "region": "Arzamas",
            "registered": "2000-09-20",
            "last_login": "2023-12-20",
            "email": "Telegin.s@gmail.com",
            "age": 7,
            },
        'Nudga' : {
            "region": "Krasnodarsk",
            "registered": "2023-05-08",
            "last_login": "88005553535",
            "email": "Nudgavsky@gmail.com",
            "age": 15,
            },
        },
    7 : {
        'Tereshin' : {
            "region": "Tuymen",
            "registered": "2006-08-11",
            "last_login": "2023-12-20",
            "email": "Artemka08@gmail.com",
            "age": 17,
            },
        'Komarov' : {
            "region": "Novorossysk",
            "registered": "2022-05-07",
            "last_login": "2023-12-20",
            "email": "i_am_not_komarov@gmail.com",
            "age": 42,
            },
        'Telegin' : {
            "region": "Arzamas",
            "registered": "2000-09-20",
            "last_login": "2023-12-20",
            "email": "Telegin.s@gmail.com",
            "age": 7,
            },
        'Nudga' : {
            "region": "Krasnodarsk",
            "registered": "2023-05-08",
            "last_login": "2023-05-30",
            "email": "Nudgavsky@gmail.com",
            "age": 'Проверка на случай, если пользователь прям совсем глупый и решит ввести строку, вместо возраста',
            },
        },
}